Repository timmo001/system-bridge, pull requests merged in 2021-07, with the labels that each got.

#459 CI Concurrency
  .github/workflows/ci.yml
Labels: ci

#460 Windows Installer
  .github/workflows/ci.yml
  .gitignore
  package.json
  public/system-bridge-win32-installer.bmp
  public/system-bridge-win32-installer.png
  scripts/installer.nsi
  scripts/post-package.js
Labels: ci, enhancement

#461 Linux Packages
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/release-drafter.yml
  .gitignore
  nfpm.yaml
  scripts/post-package.js
  scripts/system-bridge.desktop
  src/common.ts
  src/main.ts
  src/tray.ts
Labels: ci, enhancement

#469 Create shortcuts with app icons for windows
  scripts/installer.nsi
  scripts/post-package.js
Labels: enhancement

#468 Launch on startup
  package.json
  scripts/installer.nsi
  scripts/package.js
  scripts/post-package.js
  src/common.ts
  src/httpAuth.guard.ts
  src/main.ts
  src/settings/settings.service.ts
  src/tray.ts
  src/wsAuth.guard.ts
  tray/.gitignore
  tray/package.json
  tray/src/tray.ts
  tray/tsconfig.build.json
  tray/tsconfig.json
  tray/yarn.lock
  tsconfig.build.json
  yarn.lock
Labels: enhancement

#526 Use exec paths instead of working directory
  src/common.ts
  src/main.ts
  tray/src/tray.ts
Labels: bugfix

#527 Reduce package size
  .github/workflows/ci.yml
  frontend/package.json
  frontend/yarn.lock
  package.json
  scripts/installer.nsi
  scripts/package.js
  yarn.lock
Labels: enhancement

#536 Add create dmg step to CI
  .github/workflows/ci.yml
  appdmg.json
Labels: ci, refactor

#538 Create deploy workflow
  .github/workflows/deploy.yml
Labels: ci

#540 Add keyboard modifiers
  nfpm.yaml
  package.json
  src/keyboard/dto/create-keyboard.dto.ts
  src/keyboard/keyboard.service.ts
Labels: enhancement

#541 Add ability to type text using keyboard endpoint
  src/keyboard/dto/create-keyboard.dto.ts
  src/keyboard/keyboard.service.ts
Labels: enhancement

#542 Show correct version in tray and tooltip
  src/common.ts
  src/information/entities/information.entity.ts
  tray/src/tray.ts
Labels: enhancement

#543 Add USB endpoint
  nfpm.yaml
  package.json
  src/app.module.ts
  src/usb/entities/usb.entity.ts
  src/usb/usb.controller.spec.ts
  src/usb/usb.controller.ts
  src/usb/usb.module.ts
  src/usb/usb.service.spec.ts
  src/usb/usb.service.ts
Labels: new-feature

#545 Add WiFi data to network endpoint
  src/network/entities/network.entity.ts
  src/network/network.service.ts
Labels: new-feature

#547 Mac OS App Bundle
  .github/workflows/ci.yml
  appdmg.json
  scripts/Info.plist
  scripts/package.js
  src/main.ts
  tray/src/tray.ts
Labels: ci

#550 Create Event and Data Observer
  frontend/src/Configuration/Configuration.tsx
  frontend/src/Configuration/Item.tsx
  nfpm.yaml
  package.json
  src/events.ts
  src/main.ts
  src/observer.ts
Labels: new-feature

#551 Update all package files
  .github/workflows/release-drafter.yml
  frontend/package.json
  nfpm.yaml
  package.json
  tray/package.json
Labels: ci

#553 Publish events to MQTT broker
  frontend/src/Configuration/Configuration.tsx
  frontend/src/Configuration/Item.tsx
  package.json
  src/common.ts
  src/events/events.gateway.ts
  src/events/events.module.ts
  src/main.ts
  yarn.lock
Labels: new-feature

#561 Replace Hide Window Solution
  .github/workflows/ci.yml
  package.json
  scripts/package.js
  scripts/windowsConsoleHide.js
  yarn.lock
Labels: bugfix

#575 Move MQTT into its own class and only connect on startup
  .github/workflows/release-drafter.yml
  frontend/src/Configuration/Configuration.tsx
  src/common.ts
  src/events/events.gateway.ts
  src/mqtt.ts
Labels: bugfix

#576 Bump Version
  frontend/package.json
  nfpm.yaml
  package.json
  tray/package.json
Labels: maintenance

#577 Only clean if not self-hosted
  .github/workflows/ci.yml
Labels: maintenance

#580 Add UUID to Settings
  frontend/src/Configuration/Configuration.tsx
Labels: enhancement

#589 Data Frontend
  frontend/package.json
  frontend/src/Common/Footer.tsx
  frontend/src/Common/Header.tsx
  frontend/src/Configuration/Configuration.tsx
  frontend/src/Data/Data.tsx
  frontend/src/Data/DataItems.tsx
  frontend/src/Main.tsx
  frontend/yarn.lock
  src/events.ts
  src/events/events.gateway.ts
  src/observer.ts
  tray/src/tray.ts
  yarn.lock
Labels: new-feature

#592 Update version to v2.3.0
  frontend/package.json
  nfpm.yaml
  package.json
  tray/package.json
Labels: maintenance

#594 Add Information endpoint to frontend
  frontend/package.json
  frontend/src/Data/Data.tsx
  nfpm.yaml
  package.json
  tray/package.json
Labels: enhancement

#598 Fix loudness import error, remove system-control and replace with own solution
  package.json
  src/audio/audio.service.ts
  src/audio/data/index.ts
  src/audio/data/unix.ts
  src/audio/data/win32.ts
  src/audio/entities/audio.entity.ts
  yarn.lock
Labels: bugfix

#600 Observer rework, add current audio to observer
  src/audio/audio.service.ts
  src/audio/data/index.ts
  src/observer.ts
Labels: enhancement

#602 Update CI to build macOS App bundle properly
  .github/workflows/ci.yml
  .gitignore
Labels: bugfix, investigation
