Repository timmo001/system-bridge, pull requests merged in 2022-07, with the labels that each got.

#1827 Websocket client response models with ids
  connector/systembridgeconnector/websocket_client.py
  shared/systembridgeshared/websocket_client.py
Labels: enhancement

#1839 Fix missing directories - Linux
  backend/systembridgebackend/autostart/linux.py
  backend/systembridgebackend/shortcut/linux.py
Labels: bugfix

#1840 Dont wait for response on exit backend
  connector/systembridgeconnector/websocket_client.py
  shared/systembridgeshared/websocket_client.py
Labels: bugfix

#1844 Rewrite notifications using frontend and add images
  backend/systembridgebackend/server/__init__.py
  backend/systembridgebackend/server/notification.py
  backend/systembridgebackend/server/websocket.py
  connector/systembridgeconnector/const.py
  connector/systembridgeconnector/models/notification.py
  frontend/pages/app/notification.tsx
  gui/systembridgegui/__main__.py
  gui/systembridgegui/window/notification.py
  schemas/notification.json
  shared/systembridgeshared/const.py
  shared/systembridgeshared/models/notification.py
Labels: new-feature

#1845 Add actions to notifications
  backend/systembridgebackend/server/notification.py
  connector/systembridgeconnector/models/notification.py
  frontend/components/Common/API.tsx
  frontend/components/Common/Layout.tsx
  frontend/pages/app/notification.tsx
  gui/systembridgegui/window/notification.py
  schemas/notification.json
  shared/systembridgeshared/models/notification.py
Labels: new-feature

#1847 Add close functionality to player window
  frontend/pages/app/player/audio.tsx
  frontend/pages/app/player/video.tsx
  gui/systembridgegui/window/player.py
Labels: enhancement

#1848 Allow URLs for media playback
  backend/systembridgebackend/server/media.py
Labels: enhancement

#1864 Fix values for multiple displays and GPUs
  backend/systembridgebackend/modules/display/__init__.py
  backend/systembridgebackend/modules/display/update.py
  backend/systembridgebackend/modules/gpu/__init__.py
  backend/systembridgebackend/modules/gpu/update.py
Labels: bugfix

#1866 Use models in WebSocket clients
  connector/systembridgeconnector/websocket_client.py
  shared/systembridgeshared/websocket_client.py
Labels: enhancement

#1868 Add correct type to WebSocket client listener callback and allow None
  connector/systembridgeconnector/websocket_client.py
  shared/systembridgeshared/websocket_client.py
Labels: enhancement

#1880 Add id to data models
  connector/systembridgeconnector/models/battery.py
  connector/systembridgeconnector/models/bridge.py
  connector/systembridgeconnector/models/cpu.py
  connector/systembridgeconnector/models/data.py
  connector/systembridgeconnector/models/disk.py
  connector/systembridgeconnector/models/display.py
  connector/systembridgeconnector/models/gpu.py
  connector/systembridgeconnector/models/memory.py
  connector/systembridgeconnector/models/network.py
  connector/systembridgeconnector/models/sensors.py
  connector/systembridgeconnector/models/system.py
  schemas/data/battery.json
  schemas/data/bridge.json
  schemas/data/cpu.json
  schemas/data/disk.json
  schemas/data/display.json
  schemas/data/gpu.json
  schemas/data/memory.json
  schemas/data/network.json
  schemas/data/sensors.json
  schemas/data/system.json
  shared/systembridgeshared/models/battery.py
  shared/systembridgeshared/models/bridge.py
  shared/systembridgeshared/models/cpu.py
  shared/systembridgeshared/models/disk.py
  shared/systembridgeshared/models/display.py
  shared/systembridgeshared/models/gpu.py
  shared/systembridgeshared/models/memory.py
  shared/systembridgeshared/models/network.py
  shared/systembridgeshared/models/sensors.py
  shared/systembridgeshared/models/system.py
Labels: enhancement

#1881 Typings for Callable
  backend/systembridgebackend/data.py
  backend/systembridgebackend/modules/listeners.py
  backend/systembridgebackend/modules/update.py
  backend/systembridgebackend/server/__init__.py
  backend/systembridgebackend/server/auth.py
  backend/systembridgebackend/server/websocket.py
  connector/systembridgeconnector/websocket_client.py
Labels: enhancement

#1882 Request certain type for WebSocket responses
  connector/systembridgeconnector/websocket_client.py
  shared/systembridgeshared/websocket_client.py
Labels: enhancement

#1874 Replace all usages of | in type strings for Python 3.9 compat
  backend/systembridgebackend/modules/battery/__init__.py
  backend/systembridgebackend/modules/cpu/__init__.py
  backend/systembridgebackend/modules/disk/__init__.py
  backend/systembridgebackend/modules/display/__init__.py
  backend/systembridgebackend/modules/gpu/__init__.py
  backend/systembridgebackend/modules/sensors/__init__.py
  backend/systembridgebackend/modules/system/__init__.py
  backend/systembridgebackend/server/media.py
  cli/systembridgecli/__main__.py
  connector/systembridgeconnector/http_client.py
  connector/systembridgeconnector/version.py
  connector/systembridgeconnector/websocket_client.py
  gui/systembridgegui/__main__.py
  gui/systembridgegui/system_tray.py
  shared/systembridgeshared/common.py
  shared/systembridgeshared/database.py
  shared/systembridgeshared/settings.py
  shared/systembridgeshared/update.py
  shared/systembridgeshared/websocket_client.py
Labels: enhancement

#1887 Allow Optional union syntax
  backend/pyproject.toml
  cli/pyproject.toml
  connector/pyproject.toml
  frontend/pyproject.toml
  gui/pyproject.toml
  shared/pyproject.toml
  windowssensors/pyproject.toml
Labels: maintenance
